### ISSUE TITLE
cann't start capture app

### ISSUE THREAD

**Issue by NelsonWang1990** [HoloTuberKit/HoloTuberKit-for-AzureKinect#3]
my SDK version is 1.4.1 when I connct Azure kinect to a PC, the KinectCapture4PC.exe cannot be started. What is going wrong with my configuratioN.

**Comment by TakashiYoshinaga** [comment]
Did you put dll files of Azure Kinect into KinectCapture4PC?
Please read below.
https://github.com/HoloTuberKit/HoloTuberKit-for-AzureKinect/blob/master/README.md#sending-hologram-pc---youtube

**Comment by NelsonWang1990** [comment]
> Did you put dll files of Azure Kinect into KinectCapture4PC? Please read below. https://github.com/HoloTuberKit/HoloTuberKit-for-AzureKinect/blob/master/README.md#sending-hologram-pc---youtube

Yes I have solved the problem. Then I have another problem now, Does the live show only work via YouTube Live now?

**Comment by NelsonWang1990** [comment]
Hi TakashiYoshinaga,
Now I have another question, does the application means the apk HoloTuberKit? Should I install the APK on my smartphone? When I install and lauch the app, there is a message that pls connct your Nreal Glasses, what does it mean?

**Comment by TakashiYoshinaga** [comment]
Before using the app you need to be able to read the text. Platforms and devices requirement to use the app are written in reaeme.

**Comment by NelsonWang1990** [comment]
> Before using the app you need to be able to read the text. Platforms and devices requirement to use the app are written in reaeme.

Hi TakashiYoshinaga,
I'm following the readme procedure, but the app for Andriod smart phone will crash when launch it. I'm sure the the smart phone I am using could support AR core service.
